name: medicare
description: Doctor Appointment App
publish_to: "none"
version: 0.9.0+3
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^0.14.0
  flutter_chat_ui: ^1.6.6

  cupertino_icons: ^1.0.5
  file_picker: ^5.2.2
  flutter_chat_types: ^3.6.0
  http: ^0.13.5
  image_picker: ^0.8.6
  intl: ^0.17.0
  mime: ^1.0.2
  open_filex: ^4.2.2
  path_provider: ^2.0.11
  uuid: ^3.0.6
  babstrap_settings_screen: ^0.1.5+1
  google_mobile_ads: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
